In [1]:
%load_ext autoreload
%autoreload 2
%aimport
%matplotlib inline

Modules to reload:
all-except-skipped

Modules to skip:

In [2]:
import os
import sys
nb_dir = os.path.dirname(os.path.split(os.getcwd())[0])
if nb_dir not in sys.path:
    sys.path.append(nb_dir)

In [3]:
from tqdm import tqdm_notebook as tqdm
import pandas as pd
from turicreate import SFrame, load_sframe
from pathlib import Path
import turicreate.aggregate as agg
import numpy as np

In [4]:
spothlight = ["SARS","MERS Coronavirus", "Avian Influenza","Ebola", "Influenza", "HIV/AIDS","Hepatitis B","Hepatitis C", "Swine Flu"]

In [5]:
diseases_id = load_sframe("Data/diseases_id.csv")
disease_names = pd.read_csv("Data/disease_names.csv")

Finished parsing file /storage/homedir/dima/Projects/ScienceDynamics/examples/Coronavirus/Data/diseases_id.csv

------------------------------------------------------

Parsing completed. Parsed 100 lines in 0.039315 secs.

Inferred types from first 100 line(s) of file as
column_type_hints=[str,int]
If parsing fails due to incorrect types, you can correct
the inferred type list above and pass it to read_csv in
the column_type_hints argument
------------------------------------------------------

Finished parsing file /storage/homedir/dima/Projects/ScienceDynamics/examples/Coronavirus/Data/diseases_id.csv

Parsing completed. Parsed 591 lines in 0.030721 secs.

## Draw Graphs

In [6]:
import json
import os
import matplotlib.pyplot as plt
import pandas as pd
import math
import glob
import ntpath
from tqdm import tqdm
from PIL import Image
from PIL import ImageFont
from PIL import ImageDraw

In [7]:
def chunks(l, n):
    # For item i in a range that is a length of l,
    for i in range(0, len(l), n):
        # Create an index range for l of n items:
        yield l[i:i + n]

def get_d(sf_corr):
    for data in sf_corr.groupby("Disease"):
        if len(data[1]) >5:
            yield data[1].sort_values("Year")

### To PDF

In [38]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from  matplotlib.ticker import FuncFormatter

sns.set(style="ticks")
def create_gird(df, col, hue,x,y,sharey=True, legend=False):

    # Initialize a grid of plots with an Axes for each walk
    grid = sns.FacetGrid(df, col=col, hue=hue, palette=sns.color_palette("hls", 4),sharey=sharey,
                         col_wrap=3, height=4.5)
    plt.gca().xaxis.set_major_formatter(FuncFormatter(lambda x, _: int(x)))

    # Draw a horizontal line to show the starting point
    grid.map(plt.axhline, y=0, ls=":", c=".5")

    # Draw a line plot to show the trajectory of each random walk
    grid.map(plt.plot, x, y)
    if legend:
        grid.add_legend()

    # Adjust the tick positions and labels
    # grid.set(xticks=np.arange(5), yticks=[-3, 3],
    #          xlim=(-.5, 4.5), ylim=(-3.5, 3.5))

    # Adjust the arrangement of the plots
    grid.fig.tight_layout(w_pad=1)
    return grid

In [8]:
def create_pdf(temp_path,pdf_name):
    # imagelist is the list with all image filenames
    res = []
    image_list = glob.glob(os.path.join(temp_path, f"*.png"))
    image_list.sort()
    for image_path in image_list:
        img = Image.open(image_path).convert("RGB")
        res.append(img)
        os.remove(image_path)

    res[0].save(f"{pdf_name}.pdf", "PDF", resolution=100.0, save_all=True, append_images=res[1:], quality=60, optimize=True)


def draw_probas_graph(graphs, output_name, output_folder, y_fields, time_field):
    rows = math.ceil(math.sqrt(len(graphs)))
    
    fig, axs = plt.subplots(rows, rows, figsize=(14, 14))
    fig.subplots_adjust(left=0.08, right=0.98, wspace=0.3, hspace=0.3)
    titles = [t for t, _ in graphs]
    graphs = [g for _, g in graphs]
    try:
        axs = axs.flatten()
    except:
        axs = [axs]
    for title, data, ax in zip(titles, graphs, axs):

        x = data[time_field]
        for  l, y in y_fields.items():
            if not data[y].isnull().values.all():
                y = np.log(data[y])
                ax.plot(x, y ,linewidth=4  ,label=l)

        ax.xaxis.set_major_locator(plt.MaxNLocator(7, integer=True))
        ax.set_title(title)
        ax.legend()
        ax.grid(True)
        # plt.title(subreddit)
        # plt.ylabel('Average edge strength')
        # plt.xlabel('Graph number')
    plt.savefig(f'{output_folder}/{output_name}.png')
    plt.clf()

## MAG

In [8]:
diseases_mag = load_sframe("Data/mag/diseases_mag.sframe")

In [ ]:
diseases_mag = load_sframe("Data/mag/diseases_med_mag.sframe")

In [10]:
diseases_mag = diseases_mag[diseases_mag["Ref Number"]>5]

#### Authors Number Per Papaer

In [11]:
total_avg_authors = diseases_mag.groupby("disease", {"avg number of authors": agg.AVG("Authors Number"),"Count": agg.COUNT()})

In [12]:
total_avg_authors.sort("avg number of authors")

Columns:
	disease	str
	avg number of authors	float
	Count	int

Rows: 316

Data:
+---------------------------+-----------------------+-------+
|          disease          | avg number of authors | Count |
+---------------------------+-----------------------+-------+
|       Inermicapsifer      |          1.0          |   2   |
|        Dipylidiasis       |          1.0          |   1   |
|       Spotted fevers      |          1.5          |   4   |
|      Endemic syphilis     |   2.4166666666666665  |   24  |
| Tropical phagedenic ulcer |          2.5          |   18  |
|      Echinostomiasis      |   2.5384615384615383  |   13  |
|    Hymenolepis diminuta   |   2.628930817610064   |  638  |
|      Fasciolopsiasis      |   2.7142857142857144  |   7   |
|    Granuloma inguinale    |   2.798387096774194   |  125  |
|       Tropical sprue      |   2.9523809523809508  |  147  |
+---------------------------+-----------------------+-------+
[316 rows x 3 columns]
Note: Only the head of the SFrame is printed.
You can use print_rows(num_rows=m, num_columns=n) to print more rows and columns.

In [13]:
total_avg_authors[total_avg_authors["disease"]=="Granuloma inguinale"]

Columns:
	disease	str
	avg number of authors	float
	Count	int

Rows: Unknown

Data:
+---------------------+-----------------------+-------+
|       disease       | avg number of authors | Count |
+---------------------+-----------------------+-------+
| Granuloma inguinale |   2.798387096774194   |  125  |
+---------------------+-----------------------+-------+
[? rows x 3 columns]
Note: Only the head of the SFrame is printed. This SFrame is lazily evaluated.
You can use sf.materialize() to force materialization.

In [14]:
total_avg_authors.sort("avg number of authors")

Columns:
	disease	str
	avg number of authors	float
	Count	int

Rows: 316

Data:
+---------------------------+-----------------------+-------+
|          disease          | avg number of authors | Count |
+---------------------------+-----------------------+-------+
|       Inermicapsifer      |          1.0          |   2   |
|        Dipylidiasis       |          1.0          |   1   |
|       Spotted fevers      |          1.5          |   4   |
|      Endemic syphilis     |   2.4166666666666665  |   24  |
| Tropical phagedenic ulcer |          2.5          |   18  |
|      Echinostomiasis      |   2.5384615384615383  |   13  |
|    Hymenolepis diminuta   |   2.628930817610064   |  638  |
|      Fasciolopsiasis      |   2.7142857142857144  |   7   |
|    Granuloma inguinale    |   2.798387096774194   |  125  |
|       Tropical sprue      |   2.9523809523809508  |  147  |
+---------------------------+-----------------------+-------+
[316 rows x 3 columns]
Note: Only the head of the SFrame is printed.
You can use print_rows(num_rows=m, num_columns=n) to print more rows and columns.

In [15]:
total_avg_authors.sort("Count", False)

Columns:
	disease	str
	avg number of authors	float
	Count	int

Rows: 316

Data:
+---------------------------+-----------------------+--------+
|          disease          | avg number of authors | Count  |
+---------------------------+-----------------------+--------+
|          HIV/AIDS         |   6.067726334673622   | 159912 |
| Escherichia coli diarrhea |   4.670768140938698   | 65126  |
|        Tuberculosis       |   5.840608428164279   | 53174  |
|         Influenza         |   6.395874152647372   | 44530  |
|        Hepatitis C        |   6.881036665719257   | 38822  |
|        Hepatitis B        |   6.310191930069072   | 31665  |
|          Malaria          |   6.353476418698362   | 28880  |
|         Pneumonia         |   5.685450313844427   | 28447  |
|       Urinary tract       |   4.731530381289554   | 17285  |
|      Cytomegalovirus      |   5.843078833022971   | 16159  |
+---------------------------+-----------------------+--------+
[316 rows x 3 columns]
Note: Only the head of the SFrame is printed.
You can use print_rows(num_rows=m, num_columns=n) to print more rows and columns.

In [16]:
total_avg_authors.sort("Count", False)

Columns:
	disease	str
	avg number of authors	float
	Count	int

Rows: 316

Data:
+---------------------------+-----------------------+--------+
|          disease          | avg number of authors | Count  |
+---------------------------+-----------------------+--------+
|          HIV/AIDS         |   6.067726334673622   | 159912 |
| Escherichia coli diarrhea |   4.670768140938698   | 65126  |
|        Tuberculosis       |   5.840608428164279   | 53174  |
|         Influenza         |   6.395874152647372   | 44530  |
|        Hepatitis C        |   6.881036665719257   | 38822  |
|        Hepatitis B        |   6.310191930069072   | 31665  |
|          Malaria          |   6.353476418698362   | 28880  |
|         Pneumonia         |   5.685450313844427   | 28447  |
|       Urinary tract       |   4.731530381289554   | 17285  |
|      Cytomegalovirus      |   5.843078833022971   | 16159  |
+---------------------------+-----------------------+--------+
[316 rows x 3 columns]
Note: Only the head of the SFrame is printed.
You can use print_rows(num_rows=m, num_columns=n) to print more rows and columns.

In [17]:
total_avg_authors = total_avg_authors[total_avg_authors["Count"]>50]

In [18]:
total_avg_authors

Columns:
	disease	str
	avg number of authors	float
	Count	int

Rows: Unknown

Data:
+-----------------------------+-----------------------+-------+
|           disease           | avg number of authors | Count |
+-----------------------------+-----------------------+-------+
|         Louping ill         |   3.6868686868686864  |   99  |
|        Sporotrichosis       |   5.079207920792076   |  508  |
|         Plesiomonas         |   3.940594059405942   |  202  |
|           Glanders          |   5.448979591836735   |   98  |
|          Sinusitis          |   4.708965111143855   |  6811 |
|      Streptococcus suis     |   6.573650503202202   |  1097 |
| Western equine encephalitis |   4.718750000000001   |   96  |
|        Herpes simplex       |   4.765102576843887   | 14128 |
|   Laryngotracheobronchitis  |   3.869047619047619   |  760  |
|          Tularemia          |   5.092979127134724   |  527  |
+-----------------------------+-----------------------+-------+
[? rows x 3 columns]
Note: Only the head of the SFrame is printed. This SFrame is lazily evaluated.
You can use sf.materialize() to force materialization.

In [19]:
total_avg_authors.filter_by(spothlight, "disease").sort("avg number of authors").save("output/Collab/avg_authors.csv")

In [28]:
year_avg_authors = diseases_mag.filter_by(total_avg_authors["disease"], "disease").groupby(["disease", "Year"], {"Average Number of Authors": agg.AVG("Authors Number"),"Count": agg.COUNT()})

In [30]:
year_avg_authors = year_avg_authors.rename({"disease":"Disease" })

In [31]:
year_avg_authors = year_avg_authors.sort(["Disease","Year"])

In [32]:
year_avg_authors_smooth= year_avg_authors[["Disease","Average Number of Authors"]].to_dataframe().groupby("Disease").rolling(3, min_periods=2).mean()

In [33]:
year_avg_authors_smooth = year_avg_authors_smooth.reset_index()

In [34]:
year_avg_authors_smooth["Year"] = year_avg_authors.to_dataframe()["Year"]

In [35]:
year_avg_authors_smooth = year_avg_authors_smooth[year_avg_authors_smooth["Disease"].isin(spothlight)]

In [36]:
year_avg_authors_smooth = year_avg_authors_smooth[year_avg_authors_smooth["Year"]>2001]

In [39]:
import datetime
import numpy as np
from matplotlib.backends.backend_pdf import PdfPages
import matplotlib.pyplot as plt

# Create the PdfPages object to which we will save the pages:
# The with statement makes sure that the PdfPages object is closed properly at
# the end of the block, even if an Exception occurs.
with PdfPages('output/Collab/corona_authors.pdf') as pdf:
    # if LaTeX is not installed or error caught, change to `usetex=False`
    plt.rc('text', usetex=False)
    plt.figure(figsize=(8, 6))
    des = list(get_d(year_avg_authors_smooth))
    for i, curr_f in enumerate(tqdm(chunks(des, 20), total=((len(des) // 20)+1))):
        create_gird(pd.concat(curr_f),"Disease","Disease","Year", "Average Number of Authors")
#         plt.title('Page')
        pdf.savefig()
        plt.close()
#         plt.clf()

100%|██████████| 1/1 [00:01<00:00,  1.97s/it]

In [47]:
import datetime
import numpy as np
from matplotlib.backends.backend_pdf import PdfPages
import matplotlib.pyplot as plt

# Create the PdfPages object to which we will save the pages:
# The with statement makes sure that the PdfPages object is closed properly at
# the end of the block, even if an Exception occurs.
with PdfPages('output/Collab/corona_authors2.pdf') as pdf:
    # if LaTeX is not installed or error caught, change to `usetex=False`
    plt.rc('text', usetex=False)
    plt.figure(figsize=(8, 6))
    des = list(get_d(year_avg_authors[year_avg_authors["Year"]>2001].filter_by(spothlight, "Disease").to_dataframe()))
    for i, curr_f in enumerate(tqdm(chunks(des, 20), total=((len(des) // 20)+1))):
        create_gird(pd.concat(curr_f),"Disease","Disease","Year", "Average Number of Authors")
#         plt.title('Page')
        pdf.savefig()
        plt.close()
#         plt.clf()

  0%|          | 0/1 [00:00<?, ?it/s]
100%|██████████| 1/1 [00:02<00:00,  2.22s/it]

#### Diseases Researchers

In [164]:
diseases_mag.head(1)

Columns:
	PaperId	int
	Rank	int
	Doi	str
	DocType	str
	PaperTitle	str
	OriginalTitle	str
	BookTitle	str
	Year	int
	Date	str
	Publisher	str
	JournalId	int
	ConferenceSeriesId	int
	ConferenceInstanceId	int
	Volume	int
	Issue	int
	FirstPage	int
	LastPage	int
	ReferenceCount	int
	CitationCount	int
	EstimatedCitation	int
	OriginalVenue	str
	CreatedDate	str
	Ref Number	int
	Total Citations by Year	dict
	Total Citations by Year without Self Citations	dict
	Authors List Sorted	array
	Authors Number	int
	Urls	list
	disease	str
	id	int

Rows: 1

Data:
+------------+-------+-------------------------------+---------+
|  PaperId   |  Rank |              Doi              | DocType |
+------------+-------+-------------------------------+---------+
| 1968760089 | 21999 | 10.1002/(SICI)1096-9071(19... | Journal |
+------------+-------+-------------------------------+---------+
+-------------------------------+-------------------------------+-----------+
|           PaperTitle          |         OriginalTitle         | BookTitle |
+-------------------------------+-------------------------------+-----------+
| analysis of the hepatitis ... | Analysis of the Hepatitis ... |           |
+-------------------------------+-------------------------------+-----------+
+------+------------+-----------+-----------+--------------------+----------------------+
| Year |    Date    | Publisher | JournalId | ConferenceSeriesId | ConferenceInstanceId |
+------+------------+-----------+-----------+--------------------+----------------------+
| 1998 | 1998-12-01 |   Wiley   |  49828768 |        None        |         None         |
+------+------------+-----------+-----------+--------------------+----------------------+
+--------+-------+-----------+----------+----------------+---------------+-------------------+-----+
| Volume | Issue | FirstPage | LastPage | ReferenceCount | CitationCount | EstimatedCitation | ... |
+--------+-------+-----------+----------+----------------+---------------+-------------------+-----+
|   56   |   4   |    294    |   299    |       28       |       7       |         7         | ... |
+--------+-------+-----------+----------+----------------+---------------+-------------------+-----+
[1 rows x 30 columns]

In [48]:
diseases_mag_authors = diseases_mag.stack("Authors List Sorted",new_column_name="author")

In [49]:
diseases_mag_authors = diseases_mag_authors[diseases_mag_authors["Year"]>2001]

In [50]:
diseases_researchers = diseases_mag_authors.groupby("disease",  { "author_count": agg.COUNT_DISTINCT("author")}).sort('author_count',ascending=False)
diseases_researchers

Columns:
	disease	str
	author_count	int

Rows: 312

Data:
+---------------------------+--------------+
|          disease          | author_count |
+---------------------------+--------------+
|          HIV/AIDS         |    290487    |
|        Tuberculosis       |    135393    |
| Escherichia coli diarrhea |    115915    |
|         Influenza         |    114541    |
|        Hepatitis C        |    101053    |
|        Hepatitis B        |    84847     |
|         Pneumonia         |    80770     |
|          Malaria          |    64097     |
|       Urinary tract       |    44070     |
|      Cytomegalovirus      |    38717     |
+---------------------------+--------------+
[312 rows x 2 columns]
Note: Only the head of the SFrame is printed.
You can use print_rows(num_rows=m, num_columns=n) to print more rows and columns.

In [51]:
diseases_researchers = diseases_researchers.filter_by(spothlight,"disease")

In [53]:
diseases_researchers.save("output/Collab/diseases_distinict_researchers_mag.csv","csv")

In [54]:
from itertools import chain

In [55]:
disease_authors = dict(zip(spothlight, [set()]*9))
res = {"Year":[],"Disease":[],"Value":[],"Type":[]}
for year in tqdm(range(2002,2019)):
    for d in spothlight:
        author_list = diseases_mag[(diseases_mag["disease"]==d)&(diseases_mag["Year"]==year)&(diseases_mag["Authors List Sorted"]!=None)]["Authors List Sorted"]
        author_list = set(chain(*author_list))
        res["Year"].append(year)
        res["Disease"].append(d)
        res["Type"].append("New Authors")
        res["Value"].append(len(author_list-disease_authors[d]))
        res["Year"].append(year)
        res["Disease"].append(d)
        res["Type"].append("Distinct Authors")
        res["Value"].append(len(author_list))
        disease_authors[d] = disease_authors[d]|author_list

  0%|          | 0/17 [00:00<?, ?it/s]
  6%|▌         | 1/17 [00:00<00:11,  1.36it/s]
 12%|█▏        | 2/17 [00:01<00:10,  1.43it/s]
 18%|█▊        | 3/17 [00:01<00:08,  1.57it/s]
 24%|██▎       | 4/17 [00:02<00:07,  1.71it/s]
 29%|██▉       | 5/17 [00:02<00:06,  1.77it/s]
 35%|███▌      | 6/17 [00:03<00:06,  1.78it/s]
 41%|████      | 7/17 [00:03<00:05,  1.83it/s]
 47%|████▋     | 8/17 [00:04<00:04,  1.87it/s]
 53%|█████▎    | 9/17 [00:04<00:04,  1.86it/s]
 59%|█████▉    | 10/17 [00:05<00:03,  1.88it/s]
 65%|██████▍   | 11/17 [00:06<00:03,  1.86it/s]
 71%|███████   | 12/17 [00:06<00:02,  1.84it/s]
 76%|███████▋  | 13/17 [00:07<00:02,  1.83it/s]
 82%|████████▏ | 14/17 [00:07<00:01,  1.84it/s]
 88%|████████▊ | 15/17 [00:08<00:01,  1.86it/s]
 94%|█████████▍| 16/17 [00:08<00:00,  1.75it/s]
100%|██████████| 17/17 [00:09<00:00,  1.76it/s]

In [56]:
new_authors = pd.DataFrame(res)

In [57]:
new_authors = new_authors.sort_values(["Disease", "Year"])

In [58]:
import datetime
import numpy as np
from matplotlib.backends.backend_pdf import PdfPages
import matplotlib.pyplot as plt

# Create the PdfPages object to which we will save the pages:
# The with statement makes sure that the PdfPages object is closed properly at
# the end of the block, even if an Exception occurs.
with PdfPages('output/Collab/new_athors2.pdf') as pdf:
    # if LaTeX is not installed or error caught, change to `usetex=False`
    plt.rc('text', usetex=False)
    plt.figure(figsize=(8, 6))
    create_gird(new_authors,"Disease","Type","Year", "Value",False, legend=True)
#         plt.title('Page')
    pdf.savefig()
    plt.close()
#         plt.clf()

In [60]:
autor_disease =  diseases_mag[(diseases_mag["Year"]>2001)&(diseases_mag["Ref Number"] >5)][["PaperId","disease","Authors List Sorted"]].stack("Authors List Sorted",new_column_name="Author")

In [61]:
autor_disease = autor_disease.filter_by(spothlight, "disease")

In [62]:
autor_disease_count = autor_disease.groupby(["disease", "Author"], {"Count":agg.COUNT()})

In [63]:
sars_count = autor_disease_count[autor_disease_count["disease"]=="SARS"]["Count"].value_counts()

In [64]:
autor_disease_count[(autor_disease_count["disease"]=="SARS")&(autor_disease_count["Count"]>1)].to_dataframe()["Count"].mean()

3.75596166703811

In [65]:
autor_disease_count[(autor_disease_count["disease"]=="HIV/AIDS")&(autor_disease_count["Count"]>1)].to_dataframe()["Count"].mean()

5.9039899048279585

In [66]:
autor_disease_count[(autor_disease_count["disease"]=="Hepatitis C")&(autor_disease_count["Count"]>1)].to_dataframe()["Count"].mean()

5.266105752305851

In [67]:
autor_disease_count[autor_disease_count["Count"]>1].to_dataframe().groupby("disease").mean()

                        Author     Count
disease
Avian Influenza   2.226739e+09  4.500765
Ebola             2.173822e+09  4.105540
HIV/AIDS          2.187300e+09  5.903990
Hepatitis B       2.200221e+09  4.443468
Hepatitis C       2.128780e+09  5.266106
Influenza         2.184362e+09  5.056413
MERS Coronavirus  2.241648e+09  3.822380
SARS              2.254396e+09  3.755962
Swine Flu         2.136971e+09  3.473130

In [68]:
autor_disease_count[autor_disease_count["Count"]>1].to_dataframe().groupby("disease").median()

                        Author  Count
disease
Avian Influenza   2.171960e+09      3
Ebola             2.174355e+09      3
HIV/AIDS          2.190243e+09      3
Hepatitis B       2.166818e+09      2
Hepatitis C       2.150739e+09      3
Influenza         2.165081e+09      3
MERS Coronavirus  2.219394e+09      2
SARS              2.222986e+09      2
Swine Flu         2.151383e+09      2

In [71]:
sars_count["Total"] = sars_count["count"]*sars_count["value"]

In [72]:
sars_count["Total"].sum()/sars_count["count"].sum()

1.9557891482454783

In [73]:
hiv_count = autor_disease_count[autor_disease_count["disease"]=="HIV/AIDS"]["Count"].value_counts()

In [74]:
hiv_count["Total"] = hiv_count["count"]*hiv_count["value"]

In [75]:
hiv_count["Total"].sum()/ hiv_count["count"].sum()

2.752550028056333

In [78]:
c_count = autor_disease_count[autor_disease_count["disease"]=="Hepatitis C"]["Count"].value_counts()

In [79]:
c_count["Total"] = c_count["count"]*c_count["value"]

In [80]:
c_count["Total"].sum()/ c_count["count"].sum()

2.199202398741255

In [82]:
new_authors[(new_authors["Disease"]=="HIV/AIDS")&(new_authors["Type"]=="New Authors")]["Value"].sum()

285562

In [83]:
from ScienceDynamics.datasets.microsoft_academic_graph import MicrosoftAcademicGraph
from ScienceDynamics.config.configs import DATASETS_BASE_DIR
mag = MicrosoftAcademicGraph(DATASETS_BASE_DIR)

In [84]:
diseases_mag_authors = diseases_mag_authors.filter_by(spothlight,"disease")

In [85]:
diseases_authors = diseases_mag.stack("Authors List Sorted",new_column_name="author")

In [86]:
authors = set(diseases_mag_authors["author"])

In [87]:
extended_papers = mag.extended_papers.stack("Authors List Sorted",new_column_name="author")

In [88]:
authors_papers = extended_papers.filter_by(list(authors),"author")

In [89]:
author_first_paper = authors_papers.groupby("author",{"Year":agg.MIN("Year")})

In [90]:
diseases_mag_authors = diseases_mag_authors.join(author_first_paper,on="author")

In [91]:
diseases_mag_authors["seniority when published"] = diseases_mag_authors["Year"] - diseases_mag_authors["Year.1"]

In [92]:
diseases_mag_authors.groupby("disease", {"seniority":agg.AVG("seniority when published"), "median":agg.QUANTILE("seniority when published", [0.5])})

Columns:
	disease	str
	seniority	float
	median	array

Rows: 9

Data:
+------------------+--------------------+--------+
|     disease      |     seniority      | median |
+------------------+--------------------+--------+
|      Ebola       | 9.732013353286572  | [5.0]  |
|   Hepatitis B    | 9.514714927994953  | [5.0]  |
|   Hepatitis C    | 11.526719343400618 | [8.0]  |
|     HIV/AIDS     | 10.836779309137679 | [7.0]  |
| Avian Influenza  |  8.47906320388612  | [5.0]  |
|    Swine Flu     | 9.297538054028545  | [5.0]  |
|       SARS       |  8.3293155232374   | [4.0]  |
|    Influenza     | 10.251775058908217 | [6.0]  |
| MERS Coronavirus | 10.448419540229867 | [7.0]  |
+------------------+--------------------+--------+
[9 rows x 3 columns]

In [30]:
diseases_mag_authors.groupby("disease", {"seniority":agg.AVG("seniority when published"), "median":agg.QUANTILE("seniority when published", [0.5])})

Columns:
	disease	str
	seniority	float
	median	array

Rows: 9

Data:
+------------------+--------------------+--------+
|     disease      |     seniority      | median |
+------------------+--------------------+--------+
|      Ebola       | 9.701338459347925  | [5.0]  |
|   Hepatitis B    | 9.441106641571501  | [5.0]  |
|   Hepatitis C    | 11.480001042630569 | [8.0]  |
|     HIV/AIDS     | 10.881297167427093 | [7.0]  |
| Avian Influenza  | 8.530194813506423  | [5.0]  |
|    Swine Flu     |  9.30429487409111  | [5.0]  |
|       SARS       | 8.354577720108392  | [4.0]  |
|    Influenza     | 10.259110881364535 | [6.0]  |
| MERS Coronavirus | 10.440699842248675 | [7.0]  |
+------------------+--------------------+--------+
[9 rows x 3 columns]

In [31]:
diseases_mag.head(1)

Columns:
	PaperId	int
	Rank	int
	Doi	str
	DocType	str
	PaperTitle	str
	OriginalTitle	str
	BookTitle	str
	Year	int
	Date	str
	Publisher	str
	JournalId	int
	ConferenceSeriesId	int
	ConferenceInstanceId	int
	Volume	int
	Issue	int
	FirstPage	int
	LastPage	int
	ReferenceCount	int
	CitationCount	int
	EstimatedCitation	int
	OriginalVenue	str
	CreatedDate	str
	Ref Number	int
	Total Citations by Year	dict
	Total Citations by Year without Self Citations	dict
	Authors List Sorted	array
	Authors Number	int
	Urls	list
	Dict of Year_Citation Number	dict
	disease	str
	id	int

Rows: 1

Data:
+------------+-------+-------------------------------+---------+
|  PaperId   |  Rank |              Doi              | DocType |
+------------+-------+-------------------------------+---------+
| 1968760089 | 21999 | 10.1002/(SICI)1096-9071(19... | Journal |
+------------+-------+-------------------------------+---------+
+-------------------------------+-------------------------------+-----------+
|           PaperTitle          |         OriginalTitle         | BookTitle |
+-------------------------------+-------------------------------+-----------+
| analysis of the hepatitis ... | Analysis of the Hepatitis ... |           |
+-------------------------------+-------------------------------+-----------+
+------+------------+-----------+-----------+--------------------+----------------------+
| Year |    Date    | Publisher | JournalId | ConferenceSeriesId | ConferenceInstanceId |
+------+------------+-----------+-----------+--------------------+----------------------+
| 1998 | 1998-12-01 |   Wiley   |  49828768 |        None        |         None         |
+------+------------+-----------+-----------+--------------------+----------------------+
+--------+-------+-----------+----------+----------------+---------------+-------------------+-----+
| Volume | Issue | FirstPage | LastPage | ReferenceCount | CitationCount | EstimatedCitation | ... |
+--------+-------+-----------+----------+----------------+---------------+-------------------+-----+
|   56   |   4   |    294    |   299    |       28       |       7       |         7         | ... |
+--------+-------+-----------+----------+----------------+---------------+-------------------+-----+
[1 rows x 31 columns]

In [93]:
diseases_mag["first_authors"] = diseases_mag["Authors List Sorted"].apply(lambda x: x[0])

Using default 12 lambda workers.

To maximize the degree of parallelism, add the following code to the beginning of the program:

"turicreate.config.set_runtime_config('TURI_DEFAULT_NUM_PYLAMBDA_WORKERS', 24)"

Note that increasing the degree of parallelism also increases the memory footprint.

In [94]:
diseases_mag["last_author"] = diseases_mag["Authors List Sorted"].apply(lambda x: x[-1])

In [95]:
diseases_mag = diseases_mag.filter_by(spothlight,"disease")

In [96]:
diseases_mag = diseases_mag.join(author_first_paper,on={"first_authors": "author"})

In [97]:
diseases_mag = diseases_mag.join(author_first_paper,on={"last_author": "author"})

In [98]:
diseases_mag["seniority when published"] = diseases_mag["Year"] - diseases_mag["Year.1"]

In [99]:
diseases_mag["seniority when published last"] = diseases_mag["Year"] - diseases_mag["Year.2"]

In [100]:
diseases_mag.groupby("disease", {"seniority first":agg.AVG("seniority when published"), "median first":agg.QUANTILE("seniority when published", [0.5]), "seniority ;ast":agg.AVG("seniority when published last"), "median last":agg.QUANTILE("seniority when published last", [0.5])})

Columns:
	disease	str
	seniority first	float
	median first	array
	seniority ;ast	float
	median last	array

Rows: 9

Data:
+------------------+--------------------+--------------+--------------------+
|     disease      |  seniority first   | median first |   seniority ;ast   |
+------------------+--------------------+--------------+--------------------+
|      Ebola       | 8.332463768115966  |    [4.0]     | 15.66231884057972  |
|   Hepatitis B    | 7.543658479894653  |    [3.0]     | 14.75780584179134  |
|   Hepatitis C    | 8.780259095761634  |    [5.0]     | 17.22574223145503  |
|     HIV/AIDS     | 7.983384683098589  |    [4.0]     | 15.294982394366277 |
| Avian Influenza  | 6.8636808136123335 |    [3.0]     | 14.325444944259745 |
|    Swine Flu     | 7.195292535305988  |    [3.0]     | 15.023402824478806 |
|       SARS       | 7.575107296137341  |    [3.0]     |  14.2612660944206  |
|    Influenza     | 8.054541246657104  |    [4.0]     | 16.577658917918374 |
| MERS Coronavirus | 8.224732461355531  |    [5.0]     | 16.86444708680144  |
+------------------+--------------------+--------------+--------------------+
+-------------+
| median last |
+-------------+
|    [14.0]   |
|    [13.0]   |
|    [15.0]   |
|    [13.0]   |
|    [12.0]   |
|    [13.0]   |
|    [12.0]   |
|    [14.0]   |
|    [15.0]   |
+-------------+
[9 rows x 5 columns]

In [101]:
res = SFrame()
for d in spothlight:
    print(d)
    sf = diseases_mag[diseases_mag["disease"]==d]
    first = sf["seniority when published"].value_counts()[:10]
    res = res.add_columns(first.rename({"value":f"first {d}", "count":f"first count {d}"}))
    last = sf["seniority when published last"].value_counts()[:10]
    res = res.add_columns(last.rename({"value":f"last {d}", "count":f"last count {d}"}))
#     print("-----First------")
#     print(sf["seniority when published"].value_counts())
#     print("-----Last------")
#     print(sf["seniority when published last"].value_counts())

SARS
MERS Coronavirus
Avian Influenza
Ebola
Influenza
HIV/AIDS
Hepatitis B
Hepatitis C
Swine Flu

In [102]:
res.save("authors2.csv")